### ISSUE TITLE
Network speed Indicator not work

### ISSUE THREAD

**Issue by sakarya1980** [RealJohnGalt/GaltsGulch-sm8150#1]
After flash the kernel t13 and t14 is Network speed indicator not Work on statusbar. On stock kernel from xtended Rom for Op7T works

![Screenshot_20210114-075038_Einstellungen](https://user-images.githubusercontent.com/32611264/104555523-53debf00-563e-11eb-9258-d8522f54e310.png)

**Comment by RealJohnGalt** [comment]
Fixed as of 369665040cc0e5add6e27d6a571e015006e20649
