### ISSUE TITLE
Issue with Fingerprint on OnePlus 7 guacamole android 11 

### ISSUE THREAD

**Issue by mosaad00** [RealJohnGalt/GaltsGulch-sm8150#3]
After flash version 2.0.3 fingerprint it's disappear on aod or lock screen i hope to fix that

**Comment by nem0-z** [comment]
> After flash version 2.0.3 fingerprint it's disappear on aod or lock screen i hope to fix that

Android 11 isn't supported anymore. You can use older version of the kernel.
